import type { InsertMenuItem } from './schema';

/**
 * Regional dishes added to the cafeteria menu. The catalog intentionally
 * covers Syrian, Lebanese, and Gulf cooking traditions.
 */
export const regionalDishes: InsertMenuItem[] = [
  // Syrian dishes
  {
    name: 'Kibbeh Bil Sanieh',
    nameAr: 'كبة بالصينية',
    description: 'Baked layers of bulgur and seasoned lamb filled with onions and toasted pine nuts',
    descriptionAr: 'طبقات مخبوزة من البرغل واللحم المتبل محشوة بالبصل والصنوبر المحمص',
    category: 'Regional Dishes',
    price: '34.99',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554',
    preparationTime: 25,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten', 'Tree Nuts'],
    dietaryTags: [],
    nutritionalInfo: { calories: 510, protein: 24, carbs: 42, fat: 25 },
  },
  {
    name: 'Aleppo Muhammara',
    nameAr: 'محمرة حلبية',
    description: 'Aleppine roasted red pepper and walnut dip with pomegranate molasses',
    descriptionAr: 'غموس حلبي من الفلفل الأحمر المشوي والجوز مع دبس الرمان',
    category: 'Regional Dishes',
    price: '22.99',
    imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767',
    preparationTime: 8,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Tree Nuts', 'Gluten'],
    dietaryTags: ['Vegan'],
    nutritionalInfo: { calories: 290, protein: 7, carbs: 24, fat: 19 },
  },
  {
    name: 'Shish Barak',
    nameAr: 'شيش برك',
    description: 'Small lamb dumplings simmered in a warm yogurt and coriander sauce',
    descriptionAr: 'قطع عجين صغيرة محشوة باللحم تغلى في صلصة اللبن والكزبرة الدافئة',
    category: 'Regional Dishes',
    price: '36.99',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d96c',
    preparationTime: 24,
    isAvailable: true,
    isSpecial: true,
    specialPrice: '31.99',
    allergens: ['Gluten', 'Dairy'],
    dietaryTags: [],
    nutritionalInfo: { calories: 480, protein: 25, carbs: 39, fat: 23 },
  },
  {
    name: 'Yalanji Vine Leaves',
    nameAr: 'يلنجي',
    description: 'Tender vine leaves stuffed with herbed rice, tomatoes, and olive oil',
    descriptionAr: 'أوراق عنب طرية محشوة بالأرز المتبل والطماطم وزيت الزيتون',
    category: 'Regional Dishes',
    price: '25.99',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
    preparationTime: 18,
    isAvailable: true,
    isSpecial: false,
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free'],
    nutritionalInfo: { calories: 260, protein: 5, carbs: 34, fat: 11 },
  },
  {
    name: 'Syrian Fatteh',
    nameAr: 'فتة شامية',
    description: 'Toasted pita layered with chickpeas, tahini yogurt, and toasted nuts',
    descriptionAr: 'خبز بيتا محمص مع الحمص ولبن الطحينة والمكسرات المحمصة',
    category: 'Regional Dishes',
    price: '27.99',
    imageUrl: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7',
    preparationTime: 12,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten', 'Dairy', 'Sesame', 'Tree Nuts'],
    dietaryTags: ['Vegetarian'],
    nutritionalInfo: { calories: 430, protein: 14, carbs: 45, fat: 21 },
  },
  {
    name: 'Kebab Halabi',
    nameAr: 'كباب حلبي',
    description: 'Aleppo-style grilled minced lamb skewers with tomato and Aleppo pepper',
    descriptionAr: 'أسياخ لحم غنم مفروم مشوية على الطريقة الحلبية مع الطماطم والفلفل الحلبي',
    category: 'Regional Dishes',
    price: '44.99',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947',
    preparationTime: 20,
    isAvailable: true,
    isSpecial: false,
    allergens: [],
    dietaryTags: ['Gluten-Free'],
    nutritionalInfo: { calories: 560, protein: 36, carbs: 18, fat: 37 },
  },
  {
    name: 'Fatteh Makdous',
    nameAr: 'فتة مكدوس',
    description: 'Eggplant and toasted pita layered with garlic yogurt, tahini, and walnuts',
    descriptionAr: 'باذنجان وخبز محمص مع لبن بالثوم والطحينة والجوز',
    category: 'Regional Dishes',
    price: '29.99',
    imageUrl: 'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7',
    preparationTime: 16,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten', 'Dairy', 'Sesame', 'Tree Nuts'],
    dietaryTags: ['Vegetarian'],
    nutritionalInfo: { calories: 390, protein: 12, carbs: 38, fat: 22 },
  },

  // Lebanese dishes
  {
    name: 'Chicken Fatteh',
    nameAr: 'فتة الدجاج',
    description: 'Shredded chicken with chickpeas, toasted pita, yogurt, and toasted almonds',
    descriptionAr: 'دجاج مفتت مع الحمص وخبز البيتا المحمص واللبن واللوز المحمص',
    category: 'Regional Dishes',
    price: '33.99',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398',
    preparationTime: 18,
    isAvailable: true,
    isSpecial: true,
    specialPrice: '28.99',
    allergens: ['Gluten', 'Dairy', 'Tree Nuts'],
    dietaryTags: [],
    nutritionalInfo: { calories: 520, protein: 31, carbs: 40, fat: 25 },
  },
  {
    name: 'Lebanese Sayadieh',
    nameAr: 'صيادية لبنانية',
    description: 'Spiced caramelized-onion rice served with tender white fish and tahini sauce',
    descriptionAr: 'أرز متبل بالبصل المكرمل يقدم مع السمك الأبيض الطري وصلصة الطحينة',
    category: 'Regional Dishes',
    price: '42.99',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2',
    preparationTime: 22,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Fish', 'Sesame'],
    dietaryTags: ['Gluten-Free'],
    nutritionalInfo: { calories: 510, protein: 32, carbs: 51, fat: 18 },
  },
  {
    name: 'Batata Harra',
    nameAr: 'بطاطا حرة',
    description: 'Crispy potatoes tossed with garlic, cilantro, chili, and lemon',
    descriptionAr: 'بطاطا مقرمشة مع الثوم والكزبرة والفلفل الحار والليمون',
    category: 'Regional Dishes',
    price: '19.99',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877',
    preparationTime: 12,
    isAvailable: true,
    isSpecial: false,
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free'],
    nutritionalInfo: { calories: 310, protein: 5, carbs: 43, fat: 13 },
  },
  {
    name: 'Lebanese Makanek',
    nameAr: 'مقانق لبنانية',
    description: 'Mini lamb sausages sautéed with pomegranate molasses and pine nuts',
    descriptionAr: 'نقانق لحم غنم صغيرة مطهوة مع دبس الرمان والصنوبر',
    category: 'Regional Dishes',
    price: '35.99',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468',
    preparationTime: 15,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Tree Nuts'],
    dietaryTags: ['Gluten-Free'],
    nutritionalInfo: { calories: 490, protein: 27, carbs: 16, fat: 34 },
  },
  {
    name: 'Arayes Lahme',
    nameAr: 'عرايس لحمة',
    description: 'Grilled pita pockets filled with seasoned minced beef, onion, and herbs',
    descriptionAr: 'أرغفة بيتا مشوية محشوة باللحم المفروم المتبل والبصل والأعشاب',
    category: 'Regional Dishes',
    price: '31.99',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783',
    preparationTime: 14,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten'],
    dietaryTags: [],
    nutritionalInfo: { calories: 470, protein: 25, carbs: 42, fat: 22 },
  },
  {
    name: 'Lebanese Tabbouleh',
    nameAr: 'تبولة لبنانية',
    description: 'Parsley, bulgur, tomato, mint, and spring onion dressed with lemon and olive oil',
    descriptionAr: 'بقدونس وبرغل وطماطم ونعناع وبصل أخضر مع الليمون وزيت الزيتون',
    category: 'Regional Dishes',
    price: '21.99',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999',
    preparationTime: 8,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten'],
    dietaryTags: ['Vegan'],
    nutritionalInfo: { calories: 180, protein: 5, carbs: 24, fat: 8 },
  },
  {
    name: 'Fattoush Salad',
    nameAr: 'فتوش',
    description: 'Crisp lettuce and seasonal vegetables with sumac dressing and toasted pita',
    descriptionAr: 'خس وخضروات موسمية مقرمشة مع تتبيلة السماق وخبز البيتا المحمص',
    category: 'Regional Dishes',
    price: '20.99',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    preparationTime: 8,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten'],
    dietaryTags: ['Vegan'],
    nutritionalInfo: { calories: 210, protein: 5, carbs: 28, fat: 9 },
  },

  // Gulf dishes
  {
    name: 'Lamb Machboos',
    nameAr: 'مكبوس اللحم',
    description: 'Slow-cooked lamb with fragrant spiced rice, dried lime, and fried onions',
    descriptionAr: 'لحم غنم مطهو ببطء مع أرز متبل بالبهارات والليمون المجفف والبصل المقلي',
    category: 'Regional Dishes',
    price: '49.99',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19',
    preparationTime: 35,
    isAvailable: true,
    isSpecial: true,
    specialPrice: '43.99',
    allergens: [],
    dietaryTags: ['Gluten-Free'],
    nutritionalInfo: { calories: 680, protein: 39, carbs: 67, fat: 27 },
  },
  {
    name: 'Chicken Mandi',
    nameAr: 'مندي الدجاج',
    description: 'Smoky roasted chicken with Yemeni-style spiced rice and tomato salsa',
    descriptionAr: 'دجاج مشوي بنكهة مدخنة مع أرز متبل على الطريقة اليمنية وصلصة الطماطم',
    category: 'Regional Dishes',
    price: '44.99',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0',
    preparationTime: 32,
    isAvailable: true,
    isSpecial: false,
    allergens: [],
    dietaryTags: ['Gluten-Free'],
    nutritionalInfo: { calories: 620, protein: 42, carbs: 64, fat: 20 },
  },
  {
    name: 'Thareed Vegetable Stew',
    nameAr: 'ثريد بالخضار',
    description: 'Gulf-style tomato and vegetable stew served over torn regag bread',
    descriptionAr: 'مرق خليجي بالطماطم والخضروات يقدم فوق خبز الرقاق المفتت',
    category: 'Regional Dishes',
    price: '28.99',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554',
    preparationTime: 22,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten'],
    dietaryTags: ['Vegan'],
    nutritionalInfo: { calories: 330, protein: 9, carbs: 49, fat: 11 },
  },
  {
    name: 'Harees',
    nameAr: 'هريس',
    description: 'Slow-cooked wheat and chicken porridge finished with ghee and cinnamon',
    descriptionAr: 'عصيدة من القمح والدجاج مطهوة ببطء وتقدم بالسمن والقرفة',
    category: 'Regional Dishes',
    price: '32.99',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554',
    preparationTime: 30,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten', 'Dairy'],
    dietaryTags: [],
    nutritionalInfo: { calories: 460, protein: 28, carbs: 48, fat: 17 },
  },
  {
    name: 'Balaleet',
    nameAr: 'بلاليط',
    description: 'Sweet saffron vermicelli topped with a delicate cardamom omelet',
    descriptionAr: 'شعيرية حلوة بالزعفران تعلوها عجة رقيقة بنكهة الهيل',
    category: 'Regional Dishes',
    price: '24.99',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307',
    preparationTime: 15,
    isAvailable: true,
    isSpecial: false,
    allergens: ['Gluten', 'Eggs', 'Dairy'],
    dietaryTags: ['Vegetarian'],
    nutritionalInfo: { calories: 390, protein: 11, carbs: 58, fat: 12 },
  },
  {
    name: 'Gulf Vegetable Salona',
    nameAr: 'صالونة خليجية بالخضار',
    description: 'Comforting Gulf tomato stew with potato, carrot, zucchini, and warm spices',
    descriptionAr: 'مرق خليجي منزلي بالطماطم والبطاطا والجزر والكوسا والبهارات الدافئة',
    category: 'Regional Dishes',
    price: '26.99',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554',
    preparationTime: 20,
    isAvailable: true,
    isSpecial: false,
    allergens: [],
    dietaryTags: ['Vegan', 'Gluten-Free'],
    nutritionalInfo: { calories: 280, protein: 7, carbs: 43, fat: 9 },
  },
];
